---
title: "IMDb Script"
author: "Sofia Villamil"
date: "2024-03-03"
output: html_document
---

### IMDB SCRAPPING

We are going to start by scraping the IMDb data base (Link: <https://www.imdb.com>). We are using the Kaggel data base filtered and save in the previous script. The data will be filled with more variables.

```{r}
rm(list = ls())
```

#### Libraries

```{r}
library(rvest)
library(dplyr)
library(readr)
library(future.apply) # parallel processing
library(httr)
```

```{r}
set_config(user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36; Sofia Villamil / sofia.v1999@gmail.com")) # You need to set your user agent here
```

### Scrapping function

```{r}
scrape_imdb <- function(imdb_id, index) {
  cat(sprintf("Scraping IMDb data for ID: %s (Observation %d)\n", imdb_id, index))
  
  url <- paste0("https://www.imdb.com/title/", imdb_id, "/?ref_=tt_ql_lang&lang=en")
  movie_page <- tryCatch({
    read_html(url)
  }, error = function(e) {
    cat("Error in fetching URL:", url, "\n")
    return(NULL)
  })
  
  if (is.null(movie_page)) return(NULL)
  
  extract_single_text <- function(node) {
    text <- html_text(node, trim = TRUE)
    if (length(text) > 0) text else NA
  }
  
  # Title
  title <- extract_single_text(movie_page %>% html_node('h1'))
  
  # Year
  year <- extract_single_text(movie_page %>% html_node('a[href*="/releaseinfo"]'))
  
  # MPAA Rating
  mpaa_rating_node <- movie_page %>% html_node('li.ipc-inline-list__item a[href*="/parentalguide/certificates"]')
  mpaa_rating <- extract_single_text(mpaa_rating_node)
  
  # Duration
  duration_nodes <- movie_page %>% html_nodes('ul.ipc-inline-list li.ipc-inline-list__item')
  duration <- grep("^[0-9]+h [0-9]+m$", html_text(duration_nodes, trim = TRUE), value = TRUE)
  duration <- if (length(duration) > 0) tail(duration, n = 1) else NA
  
  # IMDb Score
  imdb_score <- extract_single_text(movie_page %>% html_node('span.sc-bde20123-1'))
  
  # Director
  director <- extract_single_text(movie_page %>% html_node('a.ipc-metadata-list-item__list-content-item--link[href*="/name"]'))
  
  # Actors
  actors <- movie_page %>% html_nodes('a[data-testid="title-cast-item__actor"]') %>% html_text(trim = TRUE)
  first_actor <- if (length(actors) > 0) actors[1] else NA
  second_actor <- if (length(actors) > 1) actors[2] else NA
  
  # Writers
  writers <- movie_page %>% html_nodes('a.ipc-metadata-list-item__list-content-item--link[href*="/name"]') %>% html_text(trim = TRUE)
  first_writer <- if (length(writers) > 1) writers[2] else NA
  second_writer <- if (length(writers) > 2) writers[3] else NA
  
  # Release Date
  release_date <- extract_single_text(movie_page %>% html_node('a.ipc-metadata-list-item__list-content-item--link[href*="/releaseinfo"]'))
  
  # Genre
  genre <- extract_single_text(movie_page %>% html_node('a.ipc-chip.ipc-chip--on-baseAlt span.ipc-chip__text'))
  
  # Estimated Budget
  budget <- extract_single_text(movie_page %>% html_node('[data-testid="title-boxoffice-budget"] .ipc-metadata-list-item__list-content-item'))
  
  # Gross
  gross_worldwide <- extract_single_text(movie_page %>% html_node('[data-testid="title-boxoffice-cumulativeworldwidegross"] .ipc-metadata-list-item__list-content-item'))
  
  # Review
  review_title <- extract_single_text(movie_page %>% html_node('span[data-testid="review-summary"]'))
  
  feature_review <- extract_single_text(movie_page %>% html_node('div[data-testid="review-overflow"] .ipc-html-content-inner-div'))
  
  # Awards
  awards_and_nominations <- extract_single_text(movie_page %>% html_node('span.ipc-metadata-list-item__list-content-item'))
  
  oscars_nominations <- extract_single_text(movie_page %>% html_node('a.ipc-metadata-list-item__label--link[aria-label="See more awards and nominations"]'))
  
  Sys.sleep(2)  

  data.frame(
    imdb_id = imdb_id, Title = title, 
    Year = year, MPAA = mpaa_rating, Duration = duration, IMDbscore = imdb_score, Director = director,
    FirstActor = first_actor, SecondActor = second_actor, FirstWriter = first_writer,
    SecondWriter = second_writer, ReleaseDate = release_date, Genre = genre, Budget = budget,
    GrossWorldwide = gross_worldwide, TitleReview = review_title, FeatureReview = feature_review,
    AwardsAndNominations = awards_and_nominations, Oscar_Information = oscars_nominations,
    stringsAsFactors = FALSE
  )
}
 
# 1 million movie data set from keggel that is already filtered form previous script
movies <- read_csv("TMDB_movie_dataset_v11_1mill_filter.csv", show_col_types = FALSE)
 
movies <- movies %>%
  group_by(title) %>%
  filter(year == min(year)) %>%
  ungroup()

# Selecting the amount of movies to scrap, however, set to 10.
test_movies <- head(movies, 10) 

# empty data frame to store results to make less errors
scraped_data <- data.frame()

# Use parallel processing for scraping because it takes to long so this will fasten the scrapping process

plan(multisession, workers = 7) # Adjust the number of workers based on your CPU, I have 8 so I will use one less that the maximum

# Scrape data for each movie in the test data set that we choose
scraped_data_list <- future_lapply(seq_len(nrow(test_movies)), function(i) {
  scrape_imdb(test_movies$imdb_id[i], i)
})

# Combine the results into a single data frame of all the data attained
scraped_data <- bind_rows(scraped_data_list)

# suffix to be added to each column name for reference
suffix <- "_imdb"

# Appending the suffix, except the first column
scraped_data <- scraped_data %>%
  rename_with(~ paste0(., suffix), -1)

# Merge the scraped data with your existing test dataset
final_data <- left_join(test_movies, scraped_data, by = "imdb_id")

write.csv(final_data, "data_1.csv", row.names = FALSE)

# Save the final merged dataset
#write.csv(final_data, "/Scrapping and Data Part 2/movies_final_dataset_test.csv", row.names = FALSE)

```

We are now going to continue to the next script called "Box Mojo variables scrapping script_Part_3"
